# Generated by Django 5.0.3 on 2024-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_announcement_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='courses',
            field=models.ManyToManyField(to='app.course'),
        ),
    ]
