# Generated by Django 5.0.3 on 2024-03-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_details_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='courses',
        ),
    ]
