# Generated by Django 5.0.3 on 2024-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_details_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='regno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
